create table if not exists public.members (
  id text primary key,
  name text not null,
  category text not null check (category in ('Member', 'Visitor')),
  gender text not null,
  family text default '',
  marital_status text not null,
  phone text default '',
  created_at date default current_date
);

create table if not exists public.attendance (
  id bigint generated by default as identity primary key,
  member_id text references public.members(id) on delete cascade,
  date date not null,
  status text not null default 'Present',
  checked_in_at timestamptz default now(),
  unique (member_id, date)
);

alter table public.members enable row level security;
alter table public.attendance enable row level security;

create policy "authenticated users can manage members"
  on public.members for all to authenticated using (true) with check (true);
create policy "authenticated users can manage attendance"
  on public.attendance for all to authenticated using (true) with check (true);
